### ISSUE TITLE
Password display clear text，should display cipher text

### ISSUE THREAD

**Issue by alanmpc** [tunogya/chat#1]
![image](https://user-images.githubusercontent.com/28820844/218263101-986549e9-d87f-45d1-a8f5-87e22ec0aae3.png)

**Comment by tunogya** [comment]
It's a good idea to use RSA256!

**Comment by tunogya** [comment]
For the purpose of hiding characters in the user's plaintext, a better approach might be to salt and hash the original password

> It's a good idea to use RSA256!
