### ISSUE TITLE
When input Special symbols, Chinese symbols will appear

### ISSUE THREAD

**Issue by alanmpc** [tunogya/chat#2]
![image](https://user-images.githubusercontent.com/28820844/218263215-7741b634-6d0c-487a-bbba-267f9ba1b596.png)
First ！is Chinese symbols，the second is English symbols !

**Comment by tunogya** [comment]
Do you mean that the input of illegal characters should be restricted?

**Comment by alanmpc** [comment]
Yeah ，it will t prevent users from entering errors when creating passwords
