### ISSUE TITLE
Not support other special symbols,such as $%^&

### ISSUE THREAD

**Issue by alanmpc** [tunogya/chat#4]
![image](https://user-images.githubusercontent.com/28820844/218263359-80f55e01-7f3c-4837-b2ac-fde1ccf03165.png)

**Comment by tunogya** [comment]
```
const regex = /^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[@$!%*?&#.:'^])[A-Za-z\d@$!%*?&#.:'^]{12,}$/
```

Now, only support those characters. It can be updated later.

**Comment by tunogya** [comment]
[1Password](https://1password.com/password-generator/)

> Similarly, there's no need to include a specific combination of numbers, uppercase letters, lowercase letters, and symbols. Doing so doesn't necessarily make the password stronger. What's more important is that the words used are random. However, because some services have specific character requirements, the random password generator includes options to accommodate those requirements – not because it makes a stronger password, but because it makes it easier for you to create a password that works.

**Comment by tunogya** [comment]
now, no space, no chinese characters, no emoji, no full-width symbols, but at least 16 chars
