### ISSUE TITLE
User Name maybe Should be limited to English,number or Chinese only

### ISSUE THREAD

**Issue by alanmpc** [tunogya/chat#6]
![image](https://user-images.githubusercontent.com/28820844/218264387-4b33a271-220a-4b32-8667-92aa72c8cbdf.png)

**Comment by tunogya** [comment]
It's a funny way to use emoji as username.
But for the sake of memory, I agree with your suggestion.

**Comment by tunogya** [comment]
Now, only allow alphanumeric characters, underscore, and dash, no space, no special characters, no emoji
